services:
  whisper:
    build:
      context: .
    image: whisper:latest
    ports:
      - "8080:8080"
    volumes:
      - ./test_input.json:/test_input.json
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]